default: &default
  adapter: postgresql
  encoding: unicode
  host:  localhost
  username: postgres
  password: postgres
  port: 5432
  pool: 5

development:
  <<: *default
  database: loogbook_development

test:
  <<: *default
  database: loogbook_test

production:
  <<: *default
  database: loogbook_production
  